Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('login.urls')),
    path('admin/', admin.site.urls),
    path('hijau/', include('hijau.urls')),
    path('kuning/', include('kuning.urls')),
    path('merah/', include('merah.urls')),
    path('pink/', include('pink.urls')),
]

merah/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'merah'

urlpatterns = [
    path('', views.pesan_tiket, name='pesan_tiket'),
    path('lihat_transaksi/', views.lihat_transaksi, name='lihat_transaksi'),
    path('update_transaksi/', views.update_transaksi, name='update_transaksi'),
]

pink/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'pink'

urlpatterns = [
    path('detailevent/', views.detail_event, name='detail_event'),
    path('profileorganizer/', views.profile_organizer, name='profile_organizer'),
    path('sharedprofit/', views.shared_profit, name='shared_profit'),
]

merah/models.py
from django.db import models

# Create your models here.

merah/views.py
from django.shortcuts import render

def pesan_tiket(request):
	return render(request, 'pesan_tiket.html')

def lihat_transaksi(request):
	return render(request, 'lihat_transaksi.html')

def update_transaksi(request):
	return render(request, 'update_transaksi.html')

merah/templates/lihat_transaksi.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Event+</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/login/">Login</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Registration
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/regis_pengunjung/">Pengunjung</a>
                      <a class="dropdown-item" href="/regis_organizer/">Organizer</a>
                    </div>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/merah/">Pesan Tiket</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/kuning/event/view/all/1">Event</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Testimoni
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/hijau/viewtestimoni/">Testimoni Saya</a>
                      <a class="dropdown-item" href="/hijau/">Buat Testimoni</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Transaksi
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/merah/lihat_transaksi/">Transaksi Saya</a>
                      <a class="dropdown-item" href="/hijau/bayartransaksi/">Bayar Transaksi</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>

    <div style="padding-left: 50px; padding-right: 50px; padding-top: 5px;">
      <p style="font-size: 25px; text-align: center; padding-bottom: 10px; padding-top: 30px;">Transaksi Saya</p>
      <div style="padding-top: 10px;">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">No</th>
              <th scope="col">Tanggal Transaksi</th>
              <th scope="col">Waktu Transaksi</th>
              <th scope="col">Status Transaksi</th>
              <th scope="col">Total Bayar</th>
              <th scope="col">Edit</th>
              <th scope="col">Delete</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1</td>
              <td>19 Desember 2020</td>
              <td>11.40</td>
              <td>Lunas</td>
              <td>300000</td>
              <td>
                <a href = "{% url 'merah:update_transaksi' %}"><button type="button" class="btn btn-outline-secondary">edit</button></a>
              </td>
              <td>
                <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#myModal" >delete</button>
              </td>
            </tr>
            <tr>
              <td>2</td>
              <td>1 Januari 2020</td>
              <td>10.00</td>
              <td>Belum Dibayar</td>
              <td>1000000</td>
              <td>
                <a href = "{% url 'merah:update_transaksi' %}"><button type="button" class="btn btn-outline-secondary">edit</button></a>
              </td>
              <td>
                <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#myModal">delete</button>
              </td>
            </tr>
            <tr>
              <td>3</td>
              <td>21 November 2020</td>
              <td>00.40</td>
              <td>Lunas</td>
              <td>500000</td>
              <td>
                <a href = "{% url 'merah:update_transaksi' %}"><button type="button" class="btn btn-outline-secondary">edit</button></a>
              </td>
              <td>
                <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#myModal">delete</button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

  <div class="modal" id="myModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Hapus Transaksi Event</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Apakah anda yakin untuk menghapus Transaksi Event ini?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary">Ya</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Tidak</button>
      </div>
    </div>
  </div>
</div>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

merah/templates/pesan_tiket.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Event+</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/login/">Login</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Registration
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/regis_pengunjung/">Pengunjung</a>
                      <a class="dropdown-item" href="/regis_organizer/">Organizer</a>
                    </div>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/merah/">Pesan Tiket</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/kuning/event/view/all/1">Event</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Testimoni
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/hijau/viewtestimoni/">Testimoni Saya</a>
                      <a class="dropdown-item" href="/hijau/">Buat Testimoni</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Transaksi
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/merah/lihat_transaksi/">Transaksi Saya</a>
                      <a class="dropdown-item" href="/hijau/bayartransaksi/">Bayar Transaksi</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>

    <form style="padding-left: 50px; padding-right: 50px; padding-top: 10px;">
        <p style="font-size: 25px; text-align: center; padding-bottom: 10px;">Pesan Tiket Event</p>
        <div class="form-group row">
            <label for="staticEmail" class="col-sm-2 col-form-label">Tema Event</label>
            <div class="col-sm-10">
              <input type="text" readonly class="form-control-plaintext" value="Vintage">
            </div>
        </div>
        <div class="form-group row">
            <label for="staticEmail" class="col-sm-2 col-form-label">Nama Event</label>
            <div class="col-sm-10">
              <input type="text" readonly class="form-control-plaintext" value="Pentas Seni">
            </div>
        </div>
        <div class="form-group row">
            <label for="staticEmail" class="col-sm-2 col-form-label">Deskripsi</label>
            <div class="col-sm-10">
              <input type="text" readonly class="form-control-plaintext" value="Acara tahunan sekolah">
            </div>
        </div>
        <div class="form-group row">
            <label for="staticEmail" class="col-sm-2 col-form-label">Tanggal</label>
            <div class="col-sm-10">
              <input type="text" readonly class="form-control-plaintext" value="18 Desember 2020 - 19 Desember 2020">
            </div>
        </div>
        <div class="form-group row">
            <label for="staticEmail" class="col-sm-2 col-form-label">Tipe Event</label>
            <div class="col-sm-10">
              <input type="text" readonly class="form-control-plaintext" value="Musikal">
            </div>
        </div>
    </form>

    <div style="padding-left: 50px; padding-right: 50px; padding-top: 5px;">
        <div style="padding-top: 50px;">
            <label>Reguler – 300000 – 40 – 37(tersedia)</label>
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">Nama Pemesan</th>
                  <th scope="col">Email</th>
                  <th scope="col">Hapus Transaksi</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Morales</td>
                  <td>mmorales0@opera.com</td>
                  <td>
                    <button type="button" class="btn btn-outline-danger">Hapus</button></td>
                </tr>
                <tr>
                  <td>Blink Sudirman</td>
                  <td>bklink6@bloomberg.com</td>
                  <td>
                    <button type="button" class="btn btn-outline-danger">Hapus</button></td>
                </tr>
                <tr>
                  <td>Pata Pata</td>
                  <td>czapatae@ebay.com</td>
                  <td>
                    <button type="button" class="btn btn-outline-danger">Hapus</button></td>
                </tr>
              </tbody>
            </table>
            <button type="submit" class="btn btn-primary">Tambah</button>
        </div>
        <div style="padding-top: 50px;">
            <label>VVIP – 1500000 – 15 – 15(tersedia)</label>
            <table class="table">
            </table>
            <button type="submit" class="btn btn-primary">Tambah</button>
        </div>
        <div style="padding-top: 50px;">
            <label>Bisnis – 500000 – 30 – 29(tersedia)</label>
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">Nama Pemesan</th>
                  <th scope="col">Email</th>
                  <th scope="col">Hapus Transaksi</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Cevil Ambala</td>
                  <td>cevilll@timesonline.co.uk</td>
                  <td>
                    <button type="button" class="btn btn-outline-danger">Hapus</button></td>
                </tr>
              </tbody>
            </table>
            <button type="submit" class="btn btn-primary">Tambah Baris</button>
        </div>
    </div>

    <div style="padding-left: 50px; padding-right: 50px; padding-top: 50px;">
        <button type="submit" class="btn btn-primary">Buat Transaksi</button>
        <button type="submit" class="btn btn-primary">Cancel</button>
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

merah/templates/update_transaksi.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Event+</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/login/">Login</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Registration
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/regis_pengunjung/">Pengunjung</a>
                      <a class="dropdown-item" href="/regis_organizer/">Organizer</a>
                    </div>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/merah/">Pesan Tiket</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/kuning/event/view/all/1">Event</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Testimoni
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/hijau/viewtestimoni/">Testimoni Saya</a>
                      <a class="dropdown-item" href="/hijau/">Buat Testimoni</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Transaksi
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/merah/lihat_transaksi/">Transaksi Saya</a>
                      <a class="dropdown-item" href="/hijau/bayartransaksi/">Bayar Transaksi</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>

    <form style="padding-left: 50px; padding-right: 50px; padding-top: 10px;">
        <p style="font-size: 25px; text-align: center; padding-bottom: 10px;">Pesan Tiket Event</p>
        <div class="form-group row">
            <label for="staticEmail" class="col-sm-2 col-form-label">Tema Event</label>
            <div class="col-sm-10">
              <input type="text" readonly class="form-control-plaintext" value="Vintage">
            </div>
        </div>
        <div class="form-group row">
            <label for="staticEmail" class="col-sm-2 col-form-label">Nama Event</label>
            <div class="col-sm-10">
              <input type="text" readonly class="form-control-plaintext" value="Pentas Seni">
            </div>
        </div>
        <div class="form-group row">
            <label for="staticEmail" class="col-sm-2 col-form-label">Deskripsi</label>
            <div class="col-sm-10">
              <input type="text" readonly class="form-control-plaintext" value="Acara tahunan sekolah">
            </div>
        </div>
        <div class="form-group row">
            <label for="staticEmail" class="col-sm-2 col-form-label">Tanggal</label>
            <div class="col-sm-10">
              <input type="text" readonly class="form-control-plaintext" value="18 Desember 2020 - 19 Desember 2020">
            </div>
        </div>
        <div class="form-group row">
            <label for="staticEmail" class="col-sm-2 col-form-label">Tipe Event</label>
            <div class="col-sm-10">
              <input type="text" readonly class="form-control-plaintext" value="Musikal">
            </div>
        </div>
    </form>

    <div style="padding-left: 50px; padding-right: 50px; padding-top: 5px;">
        <div style="padding-top: 50px;">
            <label>Reguler – 300000 – 40 – 37(tersedia)</label>
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">Nama Pemesan</th>
                  <th scope="col">Email</th>
                  <th scope="col">Hapus Transaksi</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Morales</td>
                  <td>mmorales0@opera.com</td>
                  <td>
                    <button type="button" class="btn btn-outline-danger">Hapus</button></td>
                </tr>
                <tr>
                  <td>Blink Sudirman</td>
                  <td>bklink6@bloomberg.com</td>
                  <td>
                    <button type="button" class="btn btn-outline-danger">Hapus</button></td>
                </tr>
                <tr>
                  <td>Pata Pata</td>
                  <td>czapatae@ebay.com</td>
                  <td>
                    <button type="button" class="btn btn-outline-danger">Hapus</button></td>
                </tr>
              </tbody>
            </table>
            <button type="submit" class="btn btn-primary">Tambah</button>
        </div>
        <div style="padding-top: 50px;">
            <label>VVIP – 1500000 – 15 – 15(tersedia)</label>
            <table class="table">
            </table>
            <button type="submit" class="btn btn-primary">Tambah</button>
        </div>
        <div style="padding-top: 50px;">
            <label>Bisnis – 500000 – 30 – 29(tersedia)</label>
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">Nama Pemesan</th>
                  <th scope="col">Email</th>
                  <th scope="col">Hapus Transaksi</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Cevil Ambala</td>
                  <td>cevilll@timesonline.co.uk</td>
                  <td>
                    <button type="button" class="btn btn-outline-danger">Hapus</button></td>
                </tr>
              </tbody>
            </table>
            <button type="submit" class="btn btn-primary">Tambah Baris</button>
        </div>
    </div>

    <div style="padding-left: 50px; padding-right: 50px; padding-top: 50px;">
        <button type="submit" class="btn btn-primary">Update Transaksi</button>
        <button type="submit" class="btn btn-primary">Cancel</button>
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>