Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('login.urls')),
    path('admin/', admin.site.urls),
    path('hijau/', include('hijau.urls')),
    path('kuning/', include('kuning.urls')),
    path('merah/', include('merah.urls')),
    path('pink/', include('pink.urls')),
]

kuning/urls.py
from django.urls import path
from . import views

app_name = 'kuning'

urlpatterns = [
    path('event/view/all/<int:page>', views.viewOrg1,name='viewOrg1'),
    path('event/create/id', views.eventCreate,name='eventCreate'),
    path('event/update/id', views.eventUpdate,name='eventUpdate'),
    path('event/delete/id', views.eventDel,name='eventDel'),
]

pink/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'pink'

urlpatterns = [
    path('detailevent/', views.detail_event, name='detail_event'),
    path('profileorganizer/', views.profile_organizer, name='profile_organizer'),
    path('sharedprofit/', views.shared_profit, name='shared_profit'),
]

kuning/models.py
from django.db import models

# Create your models here.

kuning/forms.py
from django import forms
from django.db import connection

class Event(forms.Form):
    choices = [('Sosial','Sosial'),('Fashion','Fashion'),('Olahraga','Olahraga'),('Musik','Musik'),('Seni','Seni')]

    cursor = connection.cursor()
    cursor.execute('set search_path to eventplus')
    cursor.execute('select * from tipe')
    tipe = cursor.fetchall()

    namaEvent = forms.CharField(label='Nama Event',required=True)
    deskripsiEvent = forms.CharField(label='Deskripsi Event',required=True,widget=forms.Textarea)
    temaEvent = forms.ChoiceField(label='Tema Event',required=True,choices=choices,widget=forms.CheckboxSelectMultiple)
    tanggalMulai = forms.DateField(label='Tanggal Mulai',required=True,widget=forms.DateInput(attrs={'type':'date'}))#kurang
    tanggalSelesai = forms.DateField(label='Tanggal Selesai',required=True,widget=forms.DateInput(attrs={'type':'date'}))#kurang
    jamMulai = forms.TimeField(label='Jam Mulai', required=True,widget=forms.TimeInput(attrs={'type':'time'}))#kurang
    jamSelesai = forms.TimeField(label='Jam Selesai', required=True,widget=forms.TimeInput(attrs={'type':'time'}))#kurang
    tipeEvent = forms.ChoiceField(label='Tipe Event',required=True,choices=tipe,widget=forms.Select)

class Lokasi(forms.Form):
    namaGedung = forms.CharField(required=True,widget=forms.TextInput(attrs={'placeholder':'Nama Gedung'}))
    Kota = forms.CharField(required=True,widget=forms.TextInput(attrs={'placeholder':'Nama Kota'}))
    Alamat = forms.CharField(required=True,widget=forms.Textarea(attrs={'placeholder':'Alamat','rows':3}))

class DaftarTiket(forms.Form):
    namaKelas = forms.CharField(required=True,widget=forms.TextInput(attrs={'placeholder':'Nama Kelas Tiket'}))
    Tarif = forms.CharField(required=True,widget=forms.NumberInput(attrs={'placeholder':'Tarif'}))
    Kapasitas = forms.CharField(required=True,widget=forms.NumberInput(attrs={'placeholder':'Kapasitas','rows':3}))

kuning/views.py
from django.shortcuts import render
from django.db import connection
from django.core.paginator import Paginator
from .forms import Event,Lokasi,DaftarTiket

# Create your views here.
def viewOrg1(request,page):
    cursor = connection.cursor()
    cursor.execute('select * from eventplus.event')
    eventAll = cursor.fetchall()
    eventPag = Paginator(eventAll,10)
    
    pageObj = eventPag.get_page(page)

    cursor.execute('select * from eventplus.tema')
    temaAll = cursor.fetchall()

    cursor.execute('select * from eventplus.perusahaan')
    perusahaanAll = cursor.fetchall()

    cursor.execute('select * from eventplus.individu')
    individuAll = cursor.fetchall()

    cursor.execute('SELECT lpe.ID_EVENT, l.NAMA_GEDUNG, l.KOTA FROM eventplus.LOKASI_PENYELENGGARAAN_EVENT lpe, eventplus.LOKASI l WHERE l.KODE = lpe.KODE_LOKASI')
    lokasiAll = cursor.fetchall()
    role = ''
    email = ''

    if request.session._session:
        role = request.session['role']
        email = request.session['email']
    # page_number = request.GET.get('page')
    # page_obj = Paginator.get_page(page_number)
    context = {
        'eventAll' : pageObj,
        'temaAll'  : temaAll,
        'perusahaanAll' : perusahaanAll,
        'individuAll' : individuAll,
        'lokasiAll' : lokasiAll,
        'role' : role,
        'email' : email,
    }
    return render(request, 'test.html', context)

def eventCreate(request):
    cursor = connection.cursor()
    # if request.method == 'POST':

    formsEvent = Event()
    formsLokasi = Lokasi()
    formsDaftarTiket = DaftarTiket()
    context = {
        'formsEvent' : formsEvent,
        'formsLokasi': formsLokasi,
        'formsDaftarTiket' : formsDaftarTiket,
    }
    return render(request, 'buatEvent.html', context)

def eventUpdate(request):
    cursor = connection.cursor()
    # if request.method == 'POST':

    formsEvent = Event()
    formsLokasi = Lokasi()
    formsDaftarTiket = DaftarTiket()
    context = {
        'formsEvent' : formsEvent,
        'formsLokasi': formsLokasi,
        'formsDaftarTiket' : formsDaftarTiket,
    }
    return render(request, 'updateEvent.html', context)

def eventDel(request):
    return render(request, 'konfirmasiDelete.html')

kuning/templates/buatEvent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Event+ - Buat Event</title>

    <Style>
        table, th, td {
            text-align: center;
            padding-top: 5px;
            }
    </Style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/login/">Login</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Registration
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/regis_pengunjung/">Pengunjung</a>
                      <a class="dropdown-item" href="/regis_organizer/">Organizer</a>
                    </div>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/merah/">Pesan Tiket</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/kuning/event/view/all/1">Event</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Testimoni
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/hijau/viewtestimoni/">Testimoni Saya</a>
                      <a class="dropdown-item" href="/hijau/">Buat Testimoni</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Transaksi
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/merah/lihat_transaksi/">Transaksi Saya</a>
                      <a class="dropdown-item" href="/hijau/bayartransaksi/">Bayar Transaksi</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>

    <center>
        <h2>Buat Event Baru</h2>
        <br>{% csrf_token %}
        <table>
            {% for i in formsEvent %}
            <tr>
                <td><b>{{i.label}}</b></td>
                <td>{{i}}</td>
            </tr>
            {% endfor %}
            <tr>
                <td><b>Lokasi Event</b></td>
            </tr>
            <tr>
                {% for i in formsLokasi %}
                <td>{{i}}</td>
                {% endfor %}
                <td><button id='ButDelLok'>x</button></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td><button id='ButAdLok'>Tambah Row</button></td>
            </tr>

        </tr>
        <tr>
            <td><b>Daftar Kelas Tiket</b></td>
        </tr>
        <tr>
            {% for i in formsDaftarTiket %}
                <td>{{i}}</td>
            {% endfor %}
            <td><button id='ButDelDT'>x</button></td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td><button id='ButAdDT'>Tambah Row</button></td>
        </tr>
        </table>
        <br><br>
        <input type="submit" value="Buat Event">
        &nbsp;&nbsp;
        <a href="{% url 'kuning:viewOrg1' page=1 %}"><button>Cancel</button></a>
        <br><br><br><br><br>
    </center>
        <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

kuning/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Event+ - Daftar Event</title>

    <style>
        table, th, td {
            border: 1px solid black;
            text-align: center;
            padding: 5px;
          }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/login/">Login</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Registration
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/regis_pengunjung/">Pengunjung</a>
                      <a class="dropdown-item" href="/regis_organizer/">Organizer</a>
                    </div>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/merah/">Pesan Tiket</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/kuning/event/view/all/1">Event</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Testimoni
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/hijau/viewtestimoni/">Testimoni Saya</a>
                      <a class="dropdown-item" href="/hijau/">Buat Testimoni</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Transaksi
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/merah/lihat_transaksi/">Transaksi Saya</a>
                      <a class="dropdown-item" href="/hijau/bayartransaksi/">Bayar Transaksi</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    <center>
        <h2>Event+ - Daftar Event</h2>
        <br>
        <input type='text' placeholder="Search Event">
        <br><br>
        <table>
            <tr>
                <th>No</th>
                <th>Tema Event</th>
                <th>Nama Event</th>
                <th>Organizer</th>
                <th>Lokasi</th>
                <th>Tanggal</th>
                <th>Jam</th>
                <th>Kapasitas</th>
                <th>Action</th>
            </tr>
            {% for i in eventAll %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{% for j in temaAll %}
                        {% if j.0 == i.0 %}
                            {{j.1}},
                        {% endif %}
                    {% endfor %}
                </td>
                <td>{{i.1}}</td>
                <td>
                {% for j in individuAll %}
                    {% if j.0 == i.10 %}
                        {{j.2}}&nbsp;{{j.3}}
                    {% endif %}
                {% endfor %}
                {% for j in perusahaanAll %}
                    {% if j.0 == i.10 %}
                        {{j.1}}
                    {% endif %}
                {% endfor %}
                </td>
                <td>
                    {% for j in lokasiAll %}
                        {% if j.0 == i.0 %}
                            {{j.1}},&nbsp;{{j.2}}
                        {% endif %}
                    {% endfor %}
                </td>
                <td>{{i.2}} - {{i.3}}</td>
                <td>{{i.4}} - {{i.5}}</td>
                <td>{{i.8}}</td>
                {% if role == 'organizer' %}
                    {% if email == i.10 %}
                        <td>
                            <a href="{% url 'kuning:eventUpdate' %}">
                                <button>Edit</button>
                            </a>
                        <br>
                            <a href="{% url 'kuning:eventDel' %}">
                                <button>Delete</button>
                            </a>
                        </td>
                    {% endif %}
                {% elif True %}
                <td>
                    <a href="#">
                        <button class="primary-btn">Pesan Tiket</button>
                    </a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </table>
        <br>
        <a href="{% url 'kuning:eventCreate' %}"><button>Create Event</button></a>
        <br><br>

        <div class="pagination" style="color: black;">
            <span class="step-links">
                {% if eventAll.has_previous %}
                    <a href="{% url 'kuning:viewOrg1' page=1 %}">&laquo; first</a>
                    <a href="/kuning/event/view/all/{{eventAll.previous_page_number}}">previous</a>
                {% endif %}
        
                <span class="current">
                    Page {{ eventAll.number }} of {{ eventAll.paginator.num_pages }}.
                </span>
        
                {% if eventAll.has_next %}
                    <a href="/kuning/event/view/all/{{eventAll.next_page_number}}">next</a>
                    <a href="/kuning/event/view/all/{{ eventAll.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
    </center>

        <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

kuning/templates/viewHTML1organizer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Event+ - Daftar Event</title>

    <style>
        table, th, td {
            border: 1px solid black;
            text-align: center;
            padding: 5px;
          }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/login/">Login</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Registration
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/regis_pengunjung/">Pengunjung</a>
                      <a class="dropdown-item" href="/regis_organizer/">Organizer</a>
                    </div>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/merah/">Pesan Tiket</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/kuning/event/view/organizer/1">Event</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Testimoni
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/hijau/viewtestimoni/">Testimoni Saya</a>
                      <a class="dropdown-item" href="/hijau/">Buat Testimoni</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Transaksi
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/merah/lihat_transaksi/">Transaksi Saya</a>
                      <a class="dropdown-item" href="/hijau/bayartransaksi/">Bayar Transaksi</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    <center>
        <h2>Event+ - Daftar Event</h2>
        <br>
        <input type='text' placeholder="Search Event">
        <br><br>
        <table>
            <tr>
                <th>No</th>
                <th>Tema Event</th>
                <th>Nama Event</th>
                <th>Organizer</th>
                <th>Lokasi</th>
                <th>Tanggal</th>
                <th>Jam</th>
                <th>Kapasitas</th>
                <th>Action</th>
            </tr>
            <tr>
                <td>1</td>
                <td>Musik, Seni</td>
                <td>Kompes</td>
                <td>csEvent</td>
                <td>kadin, Depok</td>
                <td>2 Feb 2020 - 5 Feb 2020</td>
                <td>21:28 - 18:42</td>
                <td>453185</td>
                <td><a href="{% url 'kuning:eventUpdate' %}"><button>Edit</button></a>
                    <br>
                    <a href="{% url 'kuning:eventDel' %}"><button>Delete</button></a></td>
            </tr>
            <tr>
                <td>2</td>
                <td>Fashion, Seni</td>
                <td>Peraq</td>
                <td>mDuddy</td>
                <td>ancolita, Bekasi</td>
                <td>3 Feb 2020 - 6 Feb 2020</td>
                <td>16:57 - 10:16</td>
                <td>262241</td>
                <td>x</td>
            </tr>
            <tr>
                <td>3</td>
                <td>Fashion, Sosial</td>
                <td>CGD</td>
                <td>smartEvent</td>
                <td>macitan city, Bogor</td>
                <td>4 Feb 2020 - 7 Feb 2020</td>
                <td>14:26 - 18:15</td>
                <td>747994</td>
                <td>x</td>
            </tr>
            <tr>
                <td>4</td>
                <td>Olahraga, Sosial</td>
                <td>CXL</td>
                <td>EGR</td>
                <td>majaran, Serang</td>
                <td>5 Feb 2020 - 8 Feb 2020</td>
                <td>04:34 - 15:43</td>
                <td>649058</td>
                <td>x</td>
            </tr>
            <tr>
                <td>5</td>
                <td>Musik, Olahraga</td>
                <td>Talasik</td>
                <td>FPred</td>
                <td>picisan city, Jakarta Selatan</td>
                <td>6 Feb 2020 - 9 Feb 2020</td>
                <td>06:19 - 20:46</td>
                <td>203714</td>
                <td>x</td>
            </tr>
            <tr>
                <td>6</td>
                <td>Fashion, Musik</td>
                <td>Gabo-Gabo</td>
                <td>Lombak</td>
                <td>sky tower, Jakarta Barat</td>
                <td>7 Feb 2020 - 10 Feb 2020</td>
                <td>08:57 - 17:37</td>
                <td>265914</td>
                <td>x</td>
            </tr>
            <tr>
                <td>7</td>
                <td>Fashion, Sosial</td>
                <td>Dangdoed</td>
                <td>Shuker</td>
                <td>power city, Bogor</td>
                <td>8 Feb 2020 - 11 Feb 2020</td>
                <td>13:11 - 06:49</td>
                <td>325538</td>
                <td>x</td>
            </tr>
            <tr>
                <td>8</td>
                <td>Olahraga, Sosial</td>
                <td>Festival Golput</td>
                <td>Harfeet</td>
                <td>sukarame, Bekasi</td>
                <td>9 Feb 2020 - 12 Feb 2020</td>
                <td>20:36 - 13:36</td>
                <td>238082</td>
                <td>x</td>
            </tr>
            <tr>
                <td>9</td>
                <td>Musik, Olahraga</td>
                <td>Konser Musrik</td>
                <td>Miles</td>
                <td>botanica, Jakarta Barat</td>
                <td>10 Feb 2020 - 13 Feb 2020</td>
                <td>22:52 - 03:40</td>
                <td>463350</td>
                <td>x</td>
            </tr>
            <tr>
                <td>10</td>
                <td>Musik, Seni</td>
                <td>Tarik</td>
                <td>Cloud9</td>
                <td>makmur jaya, Depok</td>
                <td>11 Feb 2020 - 14 Feb 2020</td>
                <td>10:46 - 04:04</td>
                <td>178453</td>
                <td>x</td>
            </tr>
        </table>
        <br>
        <a href="{% url 'kuning:eventCreate' %}"><button>Create Event</button></a>
        <br><br>
        <table>
            <tr>
                <a href="#"><th><</th></a>
                <a href="#"><th style="background-color: gray;">1</th></a>
                <td><a href="{% url 'kuning:viewOrg2' %}">2</a></td>
                <th><a href="{% url 'kuning:viewOrg2' %}">></a></th>
            </tr>
        </table>
    </center>

        <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>