Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('login.urls')),
    path('admin/', admin.site.urls),
    path('hijau/', include('hijau.urls')),
    path('kuning/', include('kuning.urls')),
    path('merah/', include('merah.urls')),
    path('pink/', include('pink.urls')),
]

hijau/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'hijau'

urlpatterns = [
    path('', views.index, name='index'),
    path('viewtestimoni/', views.viewtestimoni, name='viewtestimoni'),
    path('removetestimoni/', views.removetestimoni, name='removetestimoni'),
    path('edittestimoni/', views.edittestimoni, name='edittestimoni'),
    path('bayartransaksi/', views.bayartransaksi, name='bayartransaksi'),
]

pink/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'pink'

urlpatterns = [
    path('detailevent/', views.detail_event, name='detail_event'),
    path('profileorganizer/', views.profile_organizer, name='profile_organizer'),
    path('sharedprofit/', views.shared_profit, name='shared_profit'),
]

hijau/models.py
from django.db import models

# Create your models here.

hijau/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, '12.html')

def viewtestimoni(request):
    return render(request, '13.html')

def removetestimoni(request):
    return render(request, '14b.html')

def edittestimoni(request):
    return render(request, '14a.html')

def bayartransaksi(request):
    return render(request, '11.html')
    

hijau/templates/11.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Document</title>
    <style>
      table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
      }
    </style>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/login/">Login</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Registration
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/regis_pengunjung/">Pengunjung</a>
                      <a class="dropdown-item" href="/regis_organizer/">Organizer</a>
                    </div>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/merah/">Pesan Tiket</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/kuning/event/view/all/1">Event</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Testimoni
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/hijau/viewtestimoni/">Testimoni Saya</a>
                      <a class="dropdown-item" href="/hijau/">Buat Testimoni</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Transaksi
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/merah/lihat_transaksi/">Transaksi Saya</a>
                      <a class="dropdown-item" href="/hijau/bayartransaksi/">Bayar Transaksi</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
  <center><h1>Bayar Transaksi</h1></center> <br><br>
  <h2></h2>

  <h3>Tanggal Transaksi: 2020-12-07</h3>
  <h3>Waktu Transaksi: 09:52:38</h3>
  <table>
    <tr>
      <th>No</th>
      <th>Nama Event</th>
      <th>Nama Pemilik Tiket</th>
      <th>Nama Kelas</th>
      <th>Tarif</th>
    </tr>
    <tr>
      <td>1</td>
      <td>Dangdoed</td>
      <td>Saunder Clayhill</td>
      <td>e</td>
      <td>2700000</td>
    </tr>
  </table>
  <h4 style="margin-left: 18%;">Total Bayar: Rp 2.700.000</h4>

  <br>
  <h3>Bayar dengan Dompet Digital</h3>
  <table>
    <tr>
      <th>Nama</th>
      <th>No Akun</th>
      <th>Saldo</th>
      <th>Bayar / Top-up Saldo</th>
    </tr>
    <tr>
      <td>Danana</td>
      <td>24271</td>
      <td>939247</td>
      <td><input type="button" value="Bayar"><input type="button" value="Top-Up"></td>
    </tr>
  </table>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

hijau/templates/12.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/login/">Login</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Registration
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/regis_pengunjung/">Pengunjung</a>
                      <a class="dropdown-item" href="/regis_organizer/">Organizer</a>
                    </div>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/merah/">Pesan Tiket</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/kuning/event/view/all/1">Event</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Testimoni
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/hijau/viewtestimoni/">Testimoni Saya</a>
                      <a class="dropdown-item" href="/hijau/">Buat Testimoni</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Transaksi
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/merah/lihat_transaksi/">Transaksi Saya</a>
                      <a class="dropdown-item" href="/hijau/bayartransaksi/">Bayar Transaksi</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    <center><h1>Buat Testimoni  </h1></center> <br><br>
    <h2></h2>


    <form action="#">
        <h2><label for="event"><b>Pilih Event:</b></label>
        <select name="event" id="event">
          <optgroup label="4 Desember 2020">
            <option value="volvo">Talasik</option>
          </optgroup>
          <optgroup label="27 November 2020">
            <option value="kompes">Kompes</option>
            <option value="peraq">Peraq</option>
          </optgroup>
          <optgroup label="13 November 2020">
            <option value="mpl">MPL</option>
          </optgroup>
        </select>
        <br><br>
        <label for="rating"><b>Rating:</b></label>
        <select id="rating" name="rating">
          <option value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
          <option value="4">4</option>
          <option value="5">5</option>
        </select>
        <br><br>
        <label for="img"><b>Foto:</b></label>
        <input type="file" id="foto" name="foto" accept="image/*">
        <br><br>
        <label for="isi"><b>Isi:</b></label>
        <textarea id="isi" name="isi" rows="4" cols="50"></textarea></h2>
        <br><br>
        <a href="{% url 'hijau:viewtestimoni' %}"><input type="button" value="Buat Testimoni"></a><input type="button" value="Cancel">
      </form>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

hijau/templates/13.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Document</title>
    <style>
      table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
      }

      td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
      }

      tr:nth-child(even) {
        background-color: #dddddd;
      }
    </style>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/login/">Login</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Registration
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/regis_pengunjung/">Pengunjung</a>
                      <a class="dropdown-item" href="/regis_organizer/">Organizer</a>
                    </div>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/merah/">Pesan Tiket</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/kuning/event/view/all/1">Event</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Testimoni
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/hijau/viewtestimoni/">Testimoni Saya</a>
                      <a class="dropdown-item" href="/hijau/">Buat Testimoni</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Transaksi
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/merah/lihat_transaksi/">Transaksi Saya</a>
                      <a class="dropdown-item" href="/hijau/bayartransaksi/">Bayar Transaksi</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    <center><h1>Testimoni Saya</h1></center> <br><br>
    <h2></h2>

    <center>
      <table>
        <tr>
          <th>No</th>
          <th>Timestamp</th>
          <th>Nama Event</th>
          <th>Rating</th>
          <th>Isi</th>
          <th>Foto</th>
          <th>[Edit]</th>
          <th>[Delete]</th>
        </tr>
        <tr>
          <td>1</td>
          <td>29 Nov 2020 21:32:34</td>
          <td>Open Mic</td>
          <td>4</td>
          <td>Pelawaknya lucu</td>
          <td><img src="{% static 'images/openmic.jpg' %}" width="280px"></td>
          <td><a href="{% url 'hijau:edittestimoni' %}">[Edit]</a></td>
          <td><a href="{% url 'hijau:removetestimoni' %}">[Delete]</a></td>
        </tr>
        <tr>
          <td>2</td>
          <td>20 Nov 2020 16:09:02</td>
          <td>CXL</td>
          <td>2</td>
          <td>Acara seru, tapi sayang tidak ada toilet</td>
          <td><img src="{% static 'images/cxl.jpg' %}" width="280px"></td>
          <td><a href="#">[Edit]</a></td>
          <td><a href="#">[Delete]</a></td>
        </tr>
        <tr>
          <td>3</td>
          <td>13 Oct 2020 00:25:09</td>
          <td>CGD</td>
          <td>5</td>
          <td>Pengalaman once in a lifetime, which is seru banget apalagi bisa ketemu kak raiso</td>
          <td><img src="{% static 'images/cgd.jpg' %}" width="280px"></td>
          <td><a href="#">[Edit]</a></td>
          <td><a href="#">[Delete]</a></td>
        </tr>  
      </table>
    </center>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

hijau/templates/14a.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Document</title>

</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/login/">Login</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Registration
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/regis_pengunjung/">Pengunjung</a>
                      <a class="dropdown-item" href="/regis_organizer/">Organizer</a>
                    </div>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/merah/">Pesan Tiket</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/kuning/event/view/all/1">Event</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Testimoni
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/hijau/viewtestimoni/">Testimoni Saya</a>
                      <a class="dropdown-item" href="/hijau/">Buat Testimoni</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Transaksi
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/merah/lihat_transaksi/">Transaksi Saya</a>
                      <a class="dropdown-item" href="/hijau/bayartransaksi/">Bayar Transaksi</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
  <center><h1>Update Testimoni</h1></center> <br><br>
  <h2></h2>


  <form action="#">
      <h2><label for="event"><b>Event:</b></label>
        Open Mic
      <br><br>
      <label for="rating"><b>Rating:</b></label>
      <select id="rating" name="rating">
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
      </select>
      <br><br>
      <label for="img"><b>Foto:</b></label>
      <input type="file" id="foto" name="foto" accept="image/*">
      <br><br>
      <label for="isi"><b>Isi:</b></label>
      <textarea id="isi" name="isi" rows="4" cols="50">Pelawaknya lucu</textarea></h2>
      <br><br>
      <a href="{% url 'hijau:viewtestimoni' %}"><input type="button" value="Update Testimoni"></a><a href="{% url 'hijau:viewtestimoni' %}"><input type="button" value="Cancel"></a>
    </form>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

hijau/templates/14b.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Document</title>

</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/login/">Login</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Registration
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/regis_pengunjung/">Pengunjung</a>
                      <a class="dropdown-item" href="/regis_organizer/">Organizer</a>
                    </div>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/merah/">Pesan Tiket</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/kuning/event/view/all/1">Event</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Testimoni
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/hijau/viewtestimoni/">Testimoni Saya</a>
                      <a class="dropdown-item" href="/hijau/">Buat Testimoni</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Transaksi
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/merah/lihat_transaksi/">Transaksi Saya</a>
                      <a class="dropdown-item" href="/hijau/bayartransaksi/">Bayar Transaksi</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
  <center>
    <h1>Hapus Testimoni</h1> <br><br>
    <h2>Apakah anda yakin untuk menghapus Testimoni ini?</h2>
    <a href="{% url 'hijau:viewtestimoni' %}"><input type="button" value="Ya"></a><a href="{% url 'hijau:viewtestimoni' %}"><input type="button" value="Tidak"></a>
  </center>

   	<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>